language: android
sudo: false
jdk: oraclejdk8
dist: trusty
env:
    global:
        - ANDROID_API_LEVEL=29
        - ANDROID_BUILD_TOOLS=29.0.3
        - ANDROID_ABI=armeabi-v7a
android:
    components:
        - tools
        - platform-tools
        - tools
        - build-tools-$ANDROID_BUILD_TOOLS
        - android-$ANDROID_API_LEVEL
        - extra-android-m2repository
        - sys-img-armeabi-v7a-android-22
    licenses:
        - 'android-sdk-preview-license-52d11cd2'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
script:
    - chmod +x ./gradlew
    - ./gradlew build